# Generated by Django 4.2.13 on 2024-07-19 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='convenio',
            new_name='exames',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='name',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='paciente_nome',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='timestamp',
        ),
    ]
