# Generated by Django 4.2.13 on 2024-08-05 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_textoextraido'),
    ]

    operations = [
        migrations.AddField(
            model_name='textoextraido',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='overlay_images/'),
        ),
    ]
