# Generated by Django 4.2.13 on 2024-07-19 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr', '0002_rename_convenio_exam_exames_remove_exam_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='image',
            field=models.ImageField(null=True, upload_to='exam_images/'),
        ),
    ]
